# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJCXfSh-_Hp0T-GqkVfCYyAUSLqIr_XX
"""

# Question # 1

num1 = int(input("Enter First number : "))
num2 = int(input("Enter Second number : "))
num1 = num1 + num2
num2 = num1 - num2
num1 = num1 - num2
print("Fist number : %d" %(num1))
print("Second Number : %d" %(num2))

# Question # 2

a = int(input("Enter a number : "))

if(a % 24 == 0):
  print(f"{a} is a factor of 24")
else:
  print(f"{a} is not a factor of 24")

# Question # 3

department = []

count = int(input("Enter number of department : "))

for i in range(count):
  department.append(input("Enter Department name : "))

print(f"Last department name is : {department[-1]}")

for i in range(count):
  print("Department %d : %s"% (i, department[i]))

# Question # 4

str1 = "HELLO, WORLD"
str2 = "How arE yOu"

print("Concatenated Strings are  %s" %(str1 + str2))

print("Upper case %s" %(str1.upper()))
print("Upper case %s" %(str2.upper()))

print("Lower case %s" %(str1.lower()))
print("Lower case %s" %(str1.lower()))

print("Slice str 1 %s" %(str1[5:12]))
print("Slice str 2 %s" %(str2[-5:]))

# Question # 5

start = int(input("Enter starting number : "))
end = int(input("Enter ending number : "))

for i in range(start,end):
  if(i % 2 == 0):
    print(f"{i} is even")
  else:
    print(f"{i} is odd")

# Question # 6

fruit = ["apple","cherry","orange","kiwi","melon","mango"]

fruit.remove("cherry")
fruit.remove("melon")

fruit.insert(-1,"banana")

print(fruit)

# Question # 7

marks = {"AI" : 39 , "CN" : 74 , "DS" : 42 , "PS" : 54}

# sum of marks
sum = 0
for mark in marks.values():
  sum  += mark

print(f"Marks sum is : {sum}")

# print keys and vales using for loop

for key, value in marks.items():
  print(f"{key} : {value}")

# print max mark and relative subject

max_marks = 0
max_subject = ""

min_marks = 100
min_subject = ""
for subject, mark in marks.items():
  if(mark > max_marks ):
    max_marks = mark
    max_subject = subject

print (f"MAX marks are : {max_marks}, MAX subject is : {max_subject}")

for subject, mark in marks.items():
  if(mark < min_marks ):
    min_marks = mark
    min_subject = subject

print (f"Min marks are : {min_marks}, Min subject is : {min_subject}")

from pathlib import WindowsPath
# Question # 8

class StorageMax:
  def __init__(self, length , width , height):
    self.length = length
    self.width = width
    self.height = height

  def Calculate_area(self):
    return (self.length * self.width)

  def Calclate_volume(self):
    return(self.length * self.width * self.height)

  def display(self):
    print(f"Area : {self.Calculate_area()} Volume : {self.Calclate_volume()}")

values = (
    float(input("Enter length : ")),
    float(input("Enter width : ")),
    float(input("Enter height : "))
)

storage = StorageMax(values[0],values[1],values[2])

storage.display()

print("Storage Allocation completed .... ")

# Question # 9

class FitTrack:
  def __init__(self):
    self.Cardio = set()
    self.Strength = set()
    self.Flexibility = set()
    self.Endurance = set()

  def add_exercise(self, category , exersice):
    category.add(exersice)

  def remove_exercise(self, category, exersice):
    category.remove(exersice)

  def check_exercise(self, category, exersice):
    return exersice in category

  def union(self,set1, set2):
    return set1.union(set2)

  def intersection(self, set1, set2):
    return set1.intersection(set2)

  def difference(self, set1, set2):
    return set1.difference(set2)

fit = FitTrack()

fit.add_exercise(fit.Cardio, "Running")
fit.add_exercise(fit.Cardio, "Cycling")
fit.add_exercise(fit.Strength, "Pushups")
fit.add_exercise(fit.Strength, "Running")
fit.add_exercise(fit.Flexibility, "Yoga")
fit.add_exercise(fit.Endurance, "Running")

# Remove exercise
fit.remove_exercise(fit.Cardio, "Cycling")

# Check exercise
print("Is Running in Cardio?", fit.check_exercise(fit.Cardio, "Running"))

# Union
print("Union:", fit.union(fit.Cardio, fit.Strength))

# Intersection
print("Intersection:", fit.intersection(fit.Cardio, fit.Strength))

# Difference
print("Difference:", fit.difference(fit.Cardio, fit.Strength))

# Question # 10

# Question # 10

class SafeHome:

    def __init__(self):
        self.hazards = {
            "Exposed electrical wiring": 5,
            "Gas leak smell": 5,
            "Water leakage or mold growth": 4,
            "Loose stair railings": 3,
            "Faulty smoke detectors": 4,
            "Clogged or blocked exits": 3,
            "Slippery floors without mats": 3,
            "Windows or doors that don't lock properly": 4
        }

    def calculate_score(self):
        total_score = 0

        for hazard, severity in self.hazards.items():
            answer = int(input("Have you noticed " + hazard + "? (Yes = 1, No = 0): "))

            if answer == 1:
                total_score = total_score + severity

        return total_score

    def display(self):
        score = self.calculate_score()

        print("\nTotal Safety Score:", score)

        if score > 15:
            print("Based on the hazards reported, your home may require safety improvements. It is recommended to address these issues to prevent accidents.")
        else:
            print("Based on the hazards reported, your home does not seem to have critical safety risks. However, regular maintenance is always a good idea.")


safe = SafeHome()
safe.display()