# -*- coding: utf-8 -*-
"""Practise Basic Syntax.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmNP8X9h1Iyn5-REpxm2_avDhEsRqVvo
"""

name = "Ali"
age = 22
height = 5.9
is_student = True

print(name, age, height, is_student)
print(type(age))

a = 10
b = 3

print(a + b)             # 13
print(a % b)              # 1
print(a > b)               # True
print(a > 5 and b < 5)      # True

name = input("What is your name : ")      # take name as a string
age = int(input("What is your age : "))    # Use integer typecasting

print(f"My name is {name}, And i am {age} year old.")

marks = 65

if marks >= 90:
    print("Grade: A+")
elif marks >= 70:
    print("Grade: A")
elif marks >= 50:
    print("Grade: B")
else:
    print("Fail")

for i in range(1, 6):
    print("Number:", i)

count = 0
while count < 5:
    print("Count is:", count)
    count += 1

for i in range(10):
    if i == 5:
        break
    print(i)

fruits = ["apple", "banana", "mango"]

print(fruits[0])
fruits.append("orange")
fruits.remove("banana")
print(len(fruits))

for fruit in fruits:
    print(fruit)

coordinates = (10, 20)
print(coordinates[0])

student = {"name": "Ahmed", "age": 20, "city": "Lahore"}

print(student["name"])
student["age"] = 21
student["grade"] = "A"

for key, value in student.items():
    print(f"{key} : {value}")

message = "Hello Pakistan"

print(message.upper())
print(message.split(" "))
print(message[0:5])
print(message.replace("Pakistan", "World"))

def greet(name):
    return f"Hello, {name}!"

def add_numbers(a, b):
    return a + b

print(greet("Sara"))
print(add_numbers(5, 7))

class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def introduce(self):
        print(f"Mera naam {self.name} hai aur meri age {self.age} hai.")

student1 = Student("Bilal", 21)
student1.introduce()