# -*- coding: utf-8 -*-
"""LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OV37flz0C3cQ7st2JrWczoURKygkNVqL
"""

# Question 1
a = int(input("Enter First Number : "))
b = int(input("Enter Second Number : "))

if(a>b):
  print(f"{a} is greater than {b}")
else:
  print(f"{a} is less than or equal to {b}")

# Question # 2

a = int(input("Enter a number : "))

if(a % 2 == 0):
  print(f"{a} is even ")
else:
  print(f"{a} is odd ")

# Question # 3

a = int(input("Enter a number : "))

if(a % 3 == 0 and a % 5 == 0 ):
  print(f"{a} is divisible by both 3 and 5")
else:
  print(f"{a} is not divisible by bth 3 and 5")

# Question # 4
temp = int(input("Enter temperature in celcius : "))

if(temp > 35 ):
  print("It is hot outside")
elif(temp > 20 and temp < 25):
  print("Temperature is moderate")
elif(temp < 20):
  print("temperature is cold outside")
else:
  print("No temperature info. ")

# Question # 5

savepassword = "12340000"

password = input("Enter password : ")

if(savepassword == password):
  print("Access Granted")
else:
  print("Access Denied")

# Question # 6

year = int(input("Enter year : "))

if(year % 4 == 0 ):
  print("It is a leap year ")
else:
  print("Not a leap year")